Feature/add redux
yVolkovDunice/volkov_news_php-react-redux pull request #1
Opened 2022-02-16 06:26 UTC by yVolkovDunice

2022-02-16 14:40 UTC, ekaterinagaltsova commented on client/src/redux/sagas/postSaga.js
> +    console.log('error', err.message);
убрать консоли

2022-02-16 14:43 UTC, ekaterinagaltsova commented on client/src/pages/Main/Main.jsx
> +        {!loading && !error && news.map((post) => (
А если массив новостей пустой?  Можно вывести юзеру информацию о том, что пока новостей нет

2022-02-17 11:25 UTC, ekaterinagaltsova approved these changes

2022-02-17 11:41 UTC, sergeydt requested changes

2022-02-17 11:41 UTC, sergeydt commented on client/src/components/Menu/Menu.jsx
> +      <img alt="" />
нет атрибута src

2022-02-17 11:41 UTC, sergeydt commented on client/src/components/PostCard/PostCard.jsx
> +  post: shape({}).isRequired,
не раскрыта структура shape

2022-02-17 11:41 UTC, sergeydt commented on client/src/pages/Main/Main.jsx
> +        {loading && <CircularProgress className="spinner" />}
тут лучше использовать тернарный оператор

```jsx
{loading
  ? (
    <CircularProgress className="spinner" />
  ) : (
    /* the rest */
  )
}
```

2022-02-17 11:41 UTC, sergeydt commented on client/src/redux/reducers/postReducer.js
> +  news: [],
если файл называется posts, то и тут лучше для определенности указывать posts (или хотя бы обезличенный items)

2022-02-17 11:41 UTC, sergeydt commented on client/src/redux/reducers/postReducer.js
> +  error: '',
`error: null,`

2022-02-17 11:41 UTC, sergeydt commented on client/src/redux/reducers/postReducer.js
> +  loading: false,
`isLoading`

2022-02-17 11:41 UTC, sergeydt commented on client/src/redux/reducers/postReducer.js
> +  const { response, error } = action;
сигнатура action: `{ type, payload, error }` (см док)

2022-02-17 11:41 UTC, sergeydt commented on client/src/redux/reducers/postReducer.js
> +function postReducer(state = initialState, action = {}) {
`action = {}` подразумевает, что отсутствие action.type - ок, но это не так, потому что type должен быть обязательно

2022-02-24 10:47 UTC, merged